// Manajemen Data — migrasi Excel, backup & restore.
export const DATAMGMT = {
  page: "datamgmt-page",
  tabMigration: "datamgmt-tab-migration",
  tabBackup: "datamgmt-tab-backup",
  tabRestore: "datamgmt-tab-restore",
  downloadTemplate: "datamgmt-download-template",
  downloadExport: "datamgmt-download-export",
  entityTable: "datamgmt-entity-table",
  entityRow: "datamgmt-entity-row",
  fileInput: "datamgmt-import-file",
  modeSelect: "datamgmt-import-mode",
  previewBtn: "datamgmt-import-preview",
  commitBtn: "datamgmt-import-commit",
  report: "datamgmt-import-report",
  reportTotals: "datamgmt-import-totals",
  reportEntity: "datamgmt-report-entity",
  reportRow: "datamgmt-report-row",
  downloadBackup: "datamgmt-download-backup",
  snapshotLabel: "datamgmt-snapshot-label",
  snapshotCreate: "datamgmt-snapshot-create",
  snapshotTable: "datamgmt-snapshot-table",
  snapshotRow: "datamgmt-snapshot-row",
  snapshotDownload: "datamgmt-snapshot-download",
  snapshotRestore: "datamgmt-snapshot-restore",
  snapshotDelete: "datamgmt-snapshot-delete",
  restoreFile: "datamgmt-restore-file",
  restoreInspect: "datamgmt-restore-inspect",
  restoreMeta: "datamgmt-restore-meta",
  restoreOpen: "datamgmt-restore-open",
  restoreDialog: "datamgmt-restore-dialog",
  restoreMode: "datamgmt-restore-mode",
  restoreConfirm: "datamgmt-restore-confirm",
  restoreSubmit: "datamgmt-restore-submit",
  restoreResult: "datamgmt-restore-result",
};
